### ISSUE TITLE
recorder controls not accessible by code

### ISSUE THREAD

**Issue by fx-lange** [fx-lange/unity-record-and-play#11]
methods like `StartRecording` are not accessible by code.

missing a delegate setup or change visibility of control methods

**Comment by ReallyRad** [comment]
Hi there,
Nice plugin. I'm using it to record touch gestures with Lean Touch without issues. Now I'm trying to use the recorder by code to record user input. What would be a quick way to be able to access the recorder controls by code? Would it be enough to call StartRecording() and SaveRecording() ?

thanks

**Comment by fx-lange** [comment]
Hi @ReallyRad sorry for the delay, 

yes that would be sufficient. a quick work around would be to make Start and StopRecording public. I'll try to push a proper solution in the next days.

**Comment by ReallyRad** [comment]
Hey there, 
I managed to hack a solution by setting the corresponding booleans in the base recorder which I made public, but that also broke the recorder editor. Now I'm trying to load the recording back into the player by code, so I can immediatly see how the recording went. Any pointers on how to achieve that?

thanks!

**Comment by fx-lange** [comment]
original issues solved with latest release.

@ReallyRad - I haven't looked into setting up the Unity Timeline via code. not sure if loading clips by code is supported. were you able to find a solution for your usecase?

**Comment by specsdhdeveloper** [comment]
@fx-lange
Hey there,
No, I wasn't. Custom workflows with scripting in the Timeline are tricky it seems. Should be doable though.

Cheers for the update.
